name       : firetools
version    : 0.9.46
release    : 2
source     :
    - https://nchc.dl.sourceforge.net/project/firejail/firetools/firetools-0.9.46.tar.xz : 1245c6c3aa1437ea218a78dd62ff6c06f7e22fca7b62e967ff9630b54ed3f37c
license    : GPL-2.0
component  : security
summary    : Firetools is the graphical user interface of Firejail security sandbox.
description: |
    Firetools is the graphical user interface of Firejail security sandbox.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(gl)
rundeps    :
    - firejail
    - qt5-svg
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
