name       : firetools
version    : 0.9.58
release    : 6
source     :
    - https://github.com/netblue30/firetools/archive/0.9.58.tar.gz : 809ea2278460a48159f51f5fff962c64c0d6f7111918f53e35b582396cfd0dca
license    : GPL-2.0-or-later
component  : security
summary    : Firetools is the graphical user interface of Firejail security sandbox.
description: |
    Firetools is the graphical user interface of Firejail security sandbox.
builddeps  :
    - pkgconfig(Qt5Svg)
rundeps    :
    - firejail
    - qt5-svg
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
