name       : firetools
version    : 0.9.52
release    : 3
source     :
    - https://github.com/netblue30/firetools/archive/0.9.52.tar.gz : e7c9df75dd7956f2b9a7e27d9c488fe985b4b6576762392259ef0b83cdb3660f
license    : GPL-2.0-or-later
component  : security
summary    : Firetools is the graphical user interface of Firejail security sandbox.
description: |
    Firetools is the graphical user interface of Firejail security sandbox.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(gl)
rundeps    :
    - firejail
    - qt5-svg
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
