name       : firetools
version    : 0.9.44
release    : 1
source     :
    - https://ufpr.dl.sourceforge.net/project/firejail/firetools/firetools-0.9.44.tar.bz2 : 8d9120ef9a844903be5b7b9f6e4edfe331f165bfbdefab6728ddcb8ee9f19a8f
license    : GPL-2.0
component  : security
summary    : Firetools is the graphical user interface of Firejail security sandbox.
description: |
    Firetools is the graphical user interface of Firejail security sandbox.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(gl)
rundeps    :
    - firejail
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
